### ISSUE TITLE
https://tracking.shopback.com/client/v1/events

### ISSUE THREAD

**Issue by c2xusnpq6** [FutaGuard/FutaFilter#23]
```
https://www.shopback.com.tw/nordvpn --> https://tracking.shopback.com/client/v1/events
```

**Comment by tasi788** [comment]
請提供更詳細的資訊 🤔

**Comment by c2xusnpq6** [comment]
tracker

**Comment by c2xusnpq6** [comment]
![圖片](https://user-images.githubusercontent.com/75058881/102000629-58a11200-3d24-11eb-8746-2ba671ab828f.png)
![圖片](https://user-images.githubusercontent.com/75058881/102000632-65256a80-3d24-11eb-88cc-25fb917568a6.png)

**Comment by bestpika** [comment]
有使用者會用 shopback 賺回饋
把這個擋掉的意義在哪？

**Comment by c2xusnpq6** [comment]
這個是我在shopback網站瀏覽時產生的封包 但暫時還沒有深入了解是否會影響shopback正常運作

**Comment by bestpika** [comment]
@c2xusnpq6 不知道擋了會怎樣然後要我們直接擋？
你沒看到那個 tracking 的封包裡有你的 uuid 嗎

**Comment by c2xusnpq6** [comment]
你自己去網站逛逛吧 我都還沒有用他們的服務 只是到官網逛逛而已 你自己看要不要搞　就這樣~ ８

**Comment by c2xusnpq6** [comment]
`這行為真促瞇` 😌

**Comment by tasi788** [comment]
簡單說 shopback 本身就是靠追蹤來回饋使用者，如果擋掉他這個 tracker 就整個服務不能用了，如果真要這樣不如直接 `||shopback.com` 整個擋掉來的快。
我相信就算擋掉了你提供的網址 shopback 也會發現追蹤不到而沒有提供回饋才對，如果都沒有回饋了何必使用 shopback ?

**Comment by bestpika** [comment]
@c2xusnpq6 行為促瞇的是你啦笑死
擋追蹤擋到走火入魔是吧

**Comment by bestpika** [comment]
結果 EasyList 不是針對域名加 (ﾟ∀ﾟ)

**Comment by c2xusnpq6** [comment]
> 
> 
> 結果 EasyList 不是針對域名加 (ﾟ∀ﾟ)

https://github.com/FutaGuard/FutaFilter/issues/23#issuecomment-744102237

`你自己去網站逛逛吧 我都還沒有用他們的服務 只是到官網逛逛而已 就這樣~ ８` ok?🤨

**Comment by c2xusnpq6** [comment]
> 
> 
> @c2xusnpq6 行為促瞇的是你啦笑死
> 擋追蹤擋到走火入魔是吧
> 
> 欸不對他被加到 EasyList 裡了
> 我來去加幾句油讓他拿掉好了

欸不對他被加到 FutaGuard 裡了

https://github.com/FutaGuard/FutaFilter/commit/a3d18747d533df1b918f54e3ae125b09bd054e9a

**Comment by tasi788** [comment]
> > @c2xusnpq6 行為促瞇的是你啦笑死
> > 擋追蹤擋到走火入魔是吧
> > 欸不對他被加到 EasyList 裡了
> > 我來去加幾句油讓他拿掉好了
> 
> 欸不對他被加到 FutaGuard 裡了
> 
> [a3d1874](https://github.com/FutaGuard/FutaFilter/commit/a3d18747d533df1b918f54e3ae125b09bd054e9a)

因為那是白名單

**Comment by bestpika** [comment]
> > @c2xusnpq6 行為促瞇的是你啦笑死
> > 擋追蹤擋到走火入魔是吧
> > 欸不對他被加到 EasyList 裡了
> > 我來去加幾句油讓他拿掉好了
> 
> 欸不對他被加到 FutaGuard 裡了
> 
> [a3d1874](https://github.com/FutaGuard/FutaFilter/commit/a3d18747d533df1b918f54e3ae125b09bd054e9a)

對啊，因為有規則會讓追蹤過世所以我把他加進**白名單**裡面惹

**Comment by c2xusnpq6** [comment]
@bestpika `@@||api.shopback.com.tw/whale/events^`

**Comment by tasi788** [comment]
> @FutaGuard @bestpika `@@||api.shopback.com.tw/whale/events^`

請將此 issue 關閉後重新提出。
