### ISSUE TITLE
https://bilanx.dcard.tw/v1/events

### ISSUE THREAD

**Issue by c2xusnpq6** [FutaGuard/FutaFilter#24]
```
https://www.dcard.tw/f/cycu/p/234999716 --> https://bilanx.dcard.tw/v1/events
```
![圖片](https://user-images.githubusercontent.com/75058881/102559285-7696ba00-410a-11eb-9cd2-2724354cf419.png)
![圖片](https://user-images.githubusercontent.com/75058881/102559312-8910f380-410a-11eb-89fe-d51a95c9908f.png)
![圖片](https://user-images.githubusercontent.com/75058881/102559361-a219a480-410a-11eb-94ad-6f0288e91484.png)

**Comment by c2xusnpq6** [comment]
![圖片](https://user-images.githubusercontent.com/75058881/102559625-40a60580-410b-11eb-8c89-f5ec4e53533e.png)

**Comment by c2xusnpq6** [comment]
@tasi788 @futaguard https://www.dcard.tw/service/api/v2/notifications/see

當按下`notification按鈕`的時候不只會發送看看有沒有新消息 而且會發送`有打開過`的封包

`||dcard.tw/service/api/v2/notifications/see^`?

![圖片](https://user-images.githubusercontent.com/75058881/104892202-dc49c080-59ac-11eb-9cb0-397975ce26a5.png)

**Comment by bestpika** [comment]
@c2xusnpq6 請開一個新 issue
