### ISSUE TITLE
🚀  更新清單請求 on.cc

### ISSUE THREAD

**Issue by c2xusnpq6** [FutaGuard/FutaFilter#25]
## 現在 `FutaFilter` 對他的處置是？
沒有動作

## 建議對此網域做出何種改變
新增至 https://github.com/FutaGuard/FutaFilter/blob/master/nofarm_hosts.txt

## 提出更改的理由
東方日報 (東方報業, 東網, 東網電視...) = 親共媒體

ASN編號: 10205

![圖片](https://user-images.githubusercontent.com/75058881/102679650-12e4bd80-41ec-11eb-8a5c-1ee8e9834239.png)

![圖片](https://user-images.githubusercontent.com/75058881/102679967-2ba2a280-41ef-11eb-8c91-89e2d402cccc.png)

**Comment by c0re100** [comment]
@c2xusnpq6 www

**Comment by c2xusnpq6** [comment]
https://user-images.githubusercontent.com/75058881/102572200-668cd380-4126-11eb-8ca7-d4f4defe39bd.png

**Comment by tasi788** [comment]
FutaFilter 旨在提供一個「專為臺灣人設計的廣告阻擋規則」。
這次提供的網域為 `on.cc` 其理由為親共媒體，其中親共媒體並不與廣告衝突，也不符合我們對農場文的看法。

closed.
