### ISSUE TITLE
🚀  更新清單請求 c-api-bit.shopeemobile.com seller.shopee.sg

### ISSUE THREAD

**Issue by c2xusnpq6** [FutaGuard/FutaFilter#27]
## 提出更改的理由

`https://c-api-bit.shopeemobile.com/tw/tr`
![圖片](https://user-images.githubusercontent.com/75058881/103146643-8d32b600-4787-11eb-9a72-ca4fe4c06f2e.png)

`https://seller.shopee.sg/api/pap/report`
![圖片](https://user-images.githubusercontent.com/75058881/103146661-bfdcae80-4787-11eb-86d7-2c355aca13a5.png)

**Comment by c2xusnpq6** [comment]
tracker?

**Comment by c2xusnpq6** [comment]
它會跟踪你的運動 並發送到他們的server

**Comment by c2xusnpq6** [comment]
例如 您點擊了什麼

**Comment by c2xusnpq6** [comment]
我剛剛嘗試過ban掉它 shopee看起來好像沒什麼問題

**Comment by tasi788** [comment]
這種未經詳細測試實驗的應該收錄在 experimental filter
我點我再建立。

**Comment by c2xusnpq6** [comment]
@tasi788 `log-collector.shopee.tw` `||log-collector.shopee.tw^`

**Comment by c2xusnpq6** [comment]
`@@||api.shopback.com.tw/whale/events^`

**Comment by tasi788** [comment]
已加入到實驗性清單內。
https://github.com/FutaGuard/FutaFilter/commit/783790a944b1bb59254b39e6a11684fd261272bb

**Comment by c2xusnpq6** [comment]
@tasi788 `title`改一下? 不然...
![image](https://user-images.githubusercontent.com/75058881/110420072-84d6ef80-80d5-11eb-9a9d-4258bc494ab3.png)

**Comment by tasi788** [comment]
> @tasi788 `title`改一下? 不然...
> ![image](https://user-images.githubusercontent.com/75058881/110420072-84d6ef80-80d5-11eb-9a9d-4258bc494ab3.png)

fixed https://github.com/FutaGuard/FutaFilter/commit/b9eb7aec0d26f0da9a29e022220d94bc12362566

**Comment by c2xusnpq6** [comment]
https://github.com/FutaGuard/FutaFilter/blob/master/removeparam.txt ?
