### ISSUE TITLE
🚀  更新清單請求 https://www.dcard.tw/service/api/v2/notifications/see

### ISSUE THREAD

**Issue by c2xusnpq6** [FutaGuard/FutaFilter#28]
https://www.dcard.tw/service/api/v2/notifications/see

當按下notification按鈕的時候不只會發送看看有沒有新消息 而且會發送有打開過的封包

||dcard.tw/service/api/v2/notifications/see^?

**Comment by tasi788** [comment]
請按照樣板提問。
