### ISSUE TITLE
🚀  更新清單請求 (ClearURLs Rules)

### ISSUE THREAD

**Issue by c2xusnpq6** [FutaGuard/FutaFilter#29]
https://github.com/FutaGuard/FutaFilter/blob/master/removeparam.txt

https://github.com/ClearURLs/Rules/blob/master/data.json

https://github.com/ClearURLs/Rules/blob/master/data.min.json

**Comment by tasi788** [comment]
？

**Comment by tasi788** [comment]
請依照樣板提出 issue。
