### ISSUE TITLE
mooc tracker

### ISSUE THREAD

**Issue by c2xusnpq6** [FutaGuard/FutaFilter#31]
https://i-learning.cycu.edu.tw/mooc/controllers/course_ajax.php
https://i-learning.cycu.edu.tw/mooc/controllers/course_ajax.php?actype=start
https://i-learning.cycu.edu.tw/mooc/controllers/course_ajax.php?actype=end

```
||i-learning.cycu.edu.tw/mooc/controllers/course_ajax.php^
or
/mooc/controllers/course_ajax.php (超過一所學校使用此系統)
/controllers/course_ajax.php ?
```

![image](https://user-images.githubusercontent.com/75058881/111773241-e32b7b80-88e8-11eb-9b4f-efb571a90522.png)
![image](https://user-images.githubusercontent.com/75058881/111773264-ec1c4d00-88e8-11eb-842d-6707041d8774.png)
![image](https://user-images.githubusercontent.com/75058881/111784055-e5480700-88f5-11eb-8d19-93215c2cb890.png)

**Comment by tasi788** [comment]
@c2xusnpq6 請重新編輯並依照樣板。

**Comment by c2xusnpq6** [comment]
https://www.google.com/search?q=%22mooc%2Fcontrollers%22

**Comment by tasi788** [comment]
我們歡迎各種 issue 提出，但不歡迎不遵守規則的人。
雖然 @c2xusnpq6 曾提出不少建議，但為了長久維護請使用 issue 樣板提出。

https://docs.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates

**Comment by c2xusnpq6** [comment]
@tasi788 旭聯科技的mooc產品

**Comment by c2xusnpq6** [comment]
> https://www.google.com/search?q=%22mooc%2Fcontrollers%22
> 
> ![image](https://user-images.githubusercontent.com/75058881/111788003-918bec80-88fa-11eb-8e2c-5b2bf10085ba.png)
> ![image](https://user-images.githubusercontent.com/75058881/111788018-92bd1980-88fa-11eb-9133-8d7599120a1f.png)

@tasi788 都是一樣的icon

![image](https://user-images.githubusercontent.com/75058881/111796621-4e824700-8903-11eb-8ab9-7dfd11670686.png)

**Comment by c2xusnpq6** [comment]
intitle:網路學園
https://www.google.com/search?q=intitle%3A%E7%B6%B2%E8%B7%AF%E5%AD%B8%E5%9C%92
