### ISSUE TITLE
🚀  更新清單請求 dcard.tw

### ISSUE THREAD

**Issue by c2xusnpq6** [FutaGuard/FutaFilter#36]
## 現在 `FutaFilter` 對他的處置是？
黑名單

## 建議對此網域做出何種改變
更改

## 提出更改的理由
`通知`功能失效

![image](https://user-images.githubusercontent.com/75058881/112190262-cb812980-8c3f-11eb-8d6d-ec5557a2ee4f.png)

![image](https://user-images.githubusercontent.com/75058881/112190312-d6d45500-8c3f-11eb-9ba7-37359a15ca6b.png)

**Comment by tasi788** [comment]
fixed:
https://github.com/FutaGuard/FutaFilter/commit/93ba66aa46e4eda2423edd049916a2bb367f43cc
