### ISSUE TITLE
🚀  更新清單請求 c-api-bit.shopeemobile.com

### ISSUE THREAD

**Issue by c2xusnpq6** [FutaGuard/FutaFilter#39]
## 現在 `FutaFilter` 對他的處置是？
無

## 建議對此網域做出何種改變
新增

## 提出更改的理由
tracker?

https://c-api-bit.shopeemobile.com/tw/tr
https://c-api-bit.shopeemobile.com/ph/tr
```
||c-api-bit.shopeemobile.com/*/tr^
```

https://shopee.ph/
![image](https://user-images.githubusercontent.com/75058881/113475734-f6724580-94a9-11eb-83a1-d31a6ae32a3f.png)

https://shopee.tw/
![image](https://user-images.githubusercontent.com/75058881/113475736-f7a37280-94a9-11eb-93ec-b9e99df9c500.png)

**Comment by tasi788** [comment]
沒有任何證據表明他是 tracker 的話我們不會做任何處理。

**Comment by c2xusnpq6** [comment]
任何一個頁面都會看到它的存在 不用登入也會發送封包

**Comment by c2xusnpq6** [comment]
你可以f12看看它發送了什麼出去

**Comment by tasi788** [comment]
> 任何一個頁面都會看到它的存在 不用登入也會發送封包

那為何不一併提供上來？而是需要我們要在不確定結果下通靈？

**Comment by c2xusnpq6** [comment]
![image](https://user-images.githubusercontent.com/75058881/113487457-ce570680-94ea-11eb-84de-9f3eae54ffb3.png)
![image](https://user-images.githubusercontent.com/75058881/113487488-efb7f280-94ea-11eb-915a-4bb7aec7ec5c.png)

**Comment by tasi788** [comment]
https://github.com/FutaGuard/FutaFilter/commit/32e4c5ba1bb0263c52189f9ac92ea2029f92e525

列入實驗清單觀察

**Comment by tasi788** [comment]
🔨 added 
https://github.com/FutaGuard/FutaFilter/commit/42fd963d4f62d0a223d117a2aa5a7f746801bc3d
