### ISSUE TITLE
🚀  更新清單請求 shopee.tw shopee.ph

### ISSUE THREAD

**Issue by c2xusnpq6** [FutaGuard/FutaFilter#41]
## 現在 `FutaFilter` 對他的處置是？
尚無

## 建議對此網域做出何種改變
新增

## 提出更改的理由
廣告
```
data-sqe="ad"
```
![image](https://user-images.githubusercontent.com/75058881/113521009-5ad7f680-95c9-11eb-86c8-38067b47376e.png)
![image](https://user-images.githubusercontent.com/75058881/113521052-9b377480-95c9-11eb-8eb4-6369fbcc7bc0.png)

**Comment by tasi788** [comment]
此類型廣告符合使用者需要，且已做足利益揭露。強行封鎖有害使用者瀏覽體驗。
如果有不同的見解歡迎再開。
