### ISSUE TITLE
[removeparam] [uBO] 🚀  更新清單請求 (facebook.com)

### ISSUE THREAD

**Issue by strict-block** [FutaGuard/FutaFilter#42]
## 現在 `FutaFilter` 對他的處置是？

I consider remove/rebuild: `$removeparam=/fbclid/i`

https://github.com/FutaGuard/FutaFilter/blob/a0ab4b0afad9681108794ac5c0ab8f4f914b8052/removeparam.txt#L13

## 建議對此網域做出何種改變

N/A - I don't have good quality fix now:

```python
#if ext_ublock
$removeparam=/fbclid/i,badfilter
$removeparam=/fbclid/i,domain=~l.facebook.com
#endif
```

## 提出更改的理由

List break links opened by right click on facebook domain e.g.:

1. `https://www.facebook.com/schodolaz1/posts/1926026050942478/`

    * click on "youtube" word and use "open in new page"
  
2.  fb script generate:
    ```
    https://l.facebook.com/l.php?u=https%3A%2F%2Fyoutu.be%2F_ms30IoNaBM%3Ffbclid%3DIwAR3QC5GGExh1dXHWvLSJ3iDqCnOk1nWu2GKh9d3jqtlEFabKlqgYoHyuKDU&h=AT0M87j_nMv46VKoIDJ-ptLoHMdK4Vno7O7OMJku_1_o9nbUBxxFOVm9dPAs9AuPj0gAOHP1-YUd99yWczNhxF3H7pqhs_z9psGi3xTHQXZZmVNLmuz75nV4UWs2jOQ7vORP&__tn__=%2CmH-R&c[0]=AT0cFiVf2xILqc6ZW7eOR_LidlXi2-m0ph8wIiMdSA2xDepipyN1Nn-OCPTv2HRQYRPJex7W5JzES1Y6G9dED-IoyQC4I7oFfK40Jm4s6vUmIpL5Ii8IShSdiPRudzK5klsZlthvT4sYRYKib6y2RSLPPX1pYI6uepFrvaZOmkx4pGE
    ```
3. the removeparam filter cleared url path into (gone `u=` parametr):

    ```
   https://l.facebook.com/l.php?h=AT0M87j_nMv46VKoIDJ-ptLoHMdK4Vno7O7OMJku_1_o9nbUBxxFOVm9dPAs9AuPj0gAOHP1-YUd99yWczNhxF3H7pqhs_z9psGi3xTHQXZZmVNLmuz75nV4UWs2jOQ7vORP&__tn__=%2CmH-R&c[0]=AT0cFiVf2xILqc6ZW7eOR_LidlXi2-m0ph8wIiMdSA2xDepipyN1Nn-OCPTv2HRQYRPJex7W5JzES1Y6G9dED-IoyQC4I7oFfK40Jm4s6vUmIpL5Ii8IShSdiPRudzK5klsZlthvT4sYRYKib6y2RSLPPX1pYI6uepFrvaZOmkx4pGE
    ```

**Comment by tasi788** [comment]
fixed https://github.com/FutaGuard/FutaFilter/commit/26bf4163819aea77e9d54a820d689e1075764951

feel free reopen issue if theres have other problem.
