### ISSUE TITLE
🚀  更新清單請求 zuvio.com.tw

### ISSUE THREAD

**Issue by c2xusnpq6** [FutaGuard/FutaFilter#51]
## 現在 `FutaFilter` 對他的處置是？
嘸

## 建議對此網域做出何種改變
新增

## 提出更改的理由
跟踪器， 閱讀完帖子後，它將向服務器發送請求
https://irs.zuvio.com.tw/student5/chickenM/article/164440 --> https://forum.zuvio.com.tw/api/article/finish

```
forum.zuvio.com.tw/api/article/finish
irs.zuvio.com.tw/api/article/finish (not sure)
```

**Comment by tasi788** [comment]
👉 https://github.com/FutaGuard/FutaFilter/discussions/49
