### ISSUE TITLE
🚀  更新清單請求 dcard.tw

### ISSUE THREAD

**Issue by c2xusnpq6** [FutaGuard/FutaFilter#52]
## 現在 `FutaFilter` 對他的處置是？
嘸

## 建議對此網域做出何種改變
新增

## 提出更改的理由
當您查看完圖片並登錄後，這些將觸發並發送HTTP請求

```
||dcard.tw/service/api/v2/stories/*/view^
```
https://www.dcard.tw/f/fju
![image](https://user-images.githubusercontent.com/75058881/114821351-061b5380-9df3-11eb-8ddf-595f3d8a0346.png)

**Comment by tasi788** [comment]
他不是正常功能?

**Comment by c2xusnpq6** [comment]
> 他不是正常功能?

這個問題有點哲學 他是 但對於某些人 他不應該是 (/他可以不是 /他是 但我不想要...)
你可以參考一下 easylist, easyprivacy

**Comment by bestpika** [comment]
> > 他不是正常功能?
> 
> 這個問題有點哲學 他是 但對於某些人 他不應該是 (/他可以不是 /他是 但他對我來說 不是...)
> 你可以參考看看 easylist, easyprivacy

某些人是誰？
不要每次都「覺得」有問題就來要求我們加入清單
你看 IG 的時候會把限動擋掉嗎？

**Comment by Haraguroicha** [comment]
@bestpika 笑死

**Comment by bestpika** [comment]
@Haraguroicha 你看看你
被 github bot 陰了吼

**Comment by c2xusnpq6** [comment]
🤔

**Comment by c2xusnpq6** [comment]
ok fine~ haha
