### ISSUE TITLE
@bestpika

### ISSUE THREAD

**Issue by c2xusnpq6** [FutaGuard/FutaFilter#53]
> > > 他不是正常功能?
> > 
> > 這個問題有點哲學 他是 但對於某些人 他不應該是 (/他可以不是 /他是 但他對我來說 不是...)
> > 你可以參考看看 easylist, easyprivacy
> 
> 某些人是誰？
> 不要每次都「覺得」有問題就來要求我們加入清單
> 你看 IG 的時候會把限動擋掉嗎？
> 

你誤會了 那個不會擋限時動態 只是不發送「已讀」request而已 @bestpika

**Comment by tasi788** [comment]
> > > > 他不是正常功能?
> > > 
> > > 
> > > 這個問題有點哲學 他是 但對於某些人 他不應該是 (/他可以不是 /他是 但他對我來說 不是...)
> > > 你可以參考看看 easylist, easyprivacy
> > 
> > 
> > 某些人是誰？
> > 不要每次都「覺得」有問題就來要求我們加入清單
> > 你看 IG 的時候會把限動擋掉嗎？
> 
> 你誤會了 那個不會擋限時動態 只是不發送「已讀」request而已 @bestpika

比起這個我覺得你更需要學習如何使用 Github 各項功能，即日期停止 @c2xusnpq6 在本 repo 提出任何 issue 到 2021/04/22
