### ISSUE TITLE
🚀  更新清單請求 turtlemobile.com.tw batmobile.com.tw

### ISSUE THREAD

**Issue by c2xusnpq6** [FutaGuard/FutaFilter#54]
## 現在 `FutaFilter` 對他的處置是？
嘸

## 建議對此網域做出何種改變
新增

## 提出更改的理由
https://meteor.today/board/all --> https://backend.turtlemobile.com.tw/collector/sync
這個網站由`Data Management Platform` turtlemobile.com.tw和batmobile.com.tw提供
```
||backend.turtlemobile.com.tw/collector/*
||turtlemobile.com.tw^$third-party
||batmobile.com.tw^$third-party
```
https://www.facebook.com/BATMobileInc/
https://www.facebook.com/TurtleMobile/
![image](https://user-images.githubusercontent.com/75058881/115991978-bfe99f80-a5fd-11eb-92fc-912f9db3c94c.png)

**Comment by tasi788** [comment]
請舉出他實際做了什麼事情，例如傳輸了什麼資訊並附上截圖。

**Comment by c2xusnpq6** [comment]
還有這些

https://meteor.today/article/k5ni4A
--> https://meteor.today/ad/get_web_ad
--> https://meteor.today/adv2/get_ads
```
||meteor.today/adv2/^
||meteor.today/ad/^
```
暫時還沒接到業配
![image](https://user-images.githubusercontent.com/75058881/115996099-8b331380-a610-11eb-8122-106e6dbb5956.png)


```
<div id="rightadboard" class="right-div">

||meteor.today/redirect/webad/^
```
![image](https://user-images.githubusercontent.com/75058881/115995937-e1ec1d80-a60f-11eb-82dd-2cb5a8fb8e70.png)
![image](https://user-images.githubusercontent.com/75058881/115996023-47400e80-a610-11eb-860b-ec73a7061d89.png)

**Comment by tasi788** [comment]
`/get_ads|` 
請求已被 AdGuard base filter 處理

另外圖片圈選的內容並非什麼廣告，我認為那是該服務的公告內容而已，並沒有任何需要處理的需要。
