### ISSUE TITLE
🚀  request to update filter (wikipedia.org)

### ISSUE THREAD

**Issue by jloqfjgk** [FutaGuard/FutaFilter#60]
## what does `FutaFilter` do currently?
`$removeparam=/Campaign/i`
(https://github.com/FutaGuard/FutaFilter/blob/master/removeparam.txt#L109)

## supposed to be 
Modified so that Wikipedia's show/hide button can work correctly.

## reason
For example, on [this page](https://en.wikipedia.org/wiki/Template:Intel_processors), the "hide" button is not working (not clickable).
Once I disable the FutaFilter removeparam list, then the button works (clickable) again.

[Screenshots of expected and actual result](https://github.com/FutaGuard/FutaFilter/files/7723748/screenshots.zip)

**Comment by tasi788** [comment]
added to allow list
https://github.com/FutaGuard/FutaFilter/commit/b9ea61fca9ddbe0a8b1a242207f240fc968b4576
